import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Section } from '@/components/ui/Section'
import { formatPrice } from '@/lib/format'
import { getPublishedProgramBySlug } from '@/lib/data/programs'

type Props={params:Promise<{slug:string}>}
const find=getPublishedProgramBySlug
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params,program=await find(slug);return program?{title:program.title,description:program.description,alternates:{canonical:`/programs/${program.slug}`}}:{title:'البرنامج غير متاح',robots:{index:false,follow:false}}}
const typeLabels={bundle:'حزمة',vip:'برنامج VIP',free_resource:'مورد مجاني'} as const
export default async function ProgramDetailPage({params}:Props){const{slug}=await params,program=await find(slug);if(!program)notFound();const checkout=program.type!=='free_resource'?`/checkout/${program.type}/${program.slug}`:null;const schema={"@context":"https://schema.org","@type":"Product",name:program.title,description:program.description,offers:{"@type":"Offer",price:program.price,priceCurrency:program.currency,availability:"https://schema.org/InStock",url:`/programs/${program.slug}`}};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replaceAll('<','\\u003c')}}/><section className="bg-deep-teal px-6 py-16 text-on-dark"><div className="mx-auto max-w-5xl"><Badge tone="gold">{typeLabels[program.type]}</Badge><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-5xl">{program.title}</h1><p className="mt-3 max-w-2xl text-lg text-on-dark/75">{program.subtitle}</p><p className="mt-6 max-w-3xl leading-loose text-on-dark/85">{program.description}</p><div className="mt-7 flex flex-wrap items-center gap-4"><strong className="text-2xl text-antique-gold">{formatPrice(program.price)}</strong>{checkout?<Button href={checkout} variant="gold">ابدئي الطلب</Button>:program.resource?<Button href={`/resources/${program.resource.slug}`} variant="gold">افتحي المورد المجاني</Button>:null}</div></div></section>
      {program.type==='bundle'?<Section title="ماذا تتضمن الحزمة؟" lead="كل عنصر أدناه منشور من مصدره المتخصص؛ اختفاء عنصر أو إيقافه يمنع الحزمة من الظهور والشراء."><div className="grid gap-4 md:grid-cols-2">{program.children.map((child)=><Link key={child.href} href={child.href} className="rounded-2xl border border-line bg-surface-raised p-5 transition-colors hover:border-antique-gold"><h2 className="font-bold text-deep-teal">{child.title}</h2><p className="mt-2 text-sm text-text-soft">{child.subtitle}</p></Link>)}</div></Section>:null}
      {program.type==='vip'&&program.plan?<Section title={program.plan.title} lead={program.plan.description}><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-surface-raised p-5"><strong className="block text-2xl text-deep-teal">{program.plan.durationDays.toLocaleString('ar-EG')}</strong><span className="text-sm text-text-soft">يومًا للوصول</span></div><div className="rounded-2xl bg-surface-raised p-5"><strong className="block text-2xl text-deep-teal">{program.plan.sessionsIncluded.toLocaleString('ar-EG')}</strong><span className="text-sm text-text-soft">جلسات مشمولة</span></div><div className="rounded-2xl bg-surface-raised p-5"><strong className="block text-2xl text-deep-teal">{program.plan.maxSubscribers?.toLocaleString('ar-EG')??'—'}</strong><span className="text-sm text-text-soft">السعة القصوى إن حُددت</span></div></div>{program.plan.features.length?<ul className="mt-6 grid gap-3 md:grid-cols-2">{program.plan.features.map((feature)=><li key={feature} className="rounded-xl border border-line bg-ivory/50 p-4 text-sm text-deep-teal">{feature}</li>)}</ul>:null}</Section>:null}
      {program.type==='free_resource'&&program.resource?<Section title={program.resource.title} lead={program.resource.excerpt}><Button href={`/resources/${program.resource.slug}`}>قراءة المورد المنشور</Button></Section>:null}
    </main>}
