'use server'
import{revalidatePath}from'next/cache'
import{requirePermission}from'@/lib/auth/permissions'
import{getServiceClient}from'@/lib/supabase/server'
import{createHash}from'node:crypto'
type Result={ok:true}|{ok:false;error:string}
export async function addCustomerNote(userId:string,note:string):Promise<Result>{const admin=await requirePermission('users.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة العملاء.'};if(note.trim().length<2)return{ok:false,error:'اكتبي ملاحظة واضحة.'};const service=getServiceClient(),{error}=await service.from('user_notes').insert({user_id:userId,author_id:admin.userId,note:note.trim()});if(error)return{ok:false,error:'تعذّر حفظ الملاحظة.'};await service.from('audit_logs').insert({actor_id:admin.userId,action:'customer.note_added',entity_type:'user',entity_id:userId,meta:{length:note.trim().length}});revalidatePath(`/admin/users/${userId}`);return{ok:true}}
export async function addCustomerTag(userId:string,tag:string):Promise<Result>{const admin=await requirePermission('users.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة العملاء.'};const clean=tag.trim().slice(0,40);if(clean.length<2)return{ok:false,error:'اكتبي وسمًا واضحًا.'};const service=getServiceClient(),{error}=await service.from('user_tags').upsert({user_id:userId,tag:clean},{onConflict:'user_id,tag'});if(error)return{ok:false,error:'تعذّر حفظ الوسم.'};await service.from('audit_logs').insert({actor_id:admin.userId,action:'customer.tag_added',entity_type:'user',entity_id:userId,meta:{tag:clean}});revalidatePath(`/admin/users/${userId}`);return{ok:true}}
export async function manageInboxMessage(messageId:string,input:{status:string;priority:string;assignedTo?:string;note?:string;spam:boolean;reply?:string}):Promise<Result>{const admin=await requirePermission('inbox.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة الرسائل.'};if(!['new','read','replied','archived'].includes(input.status)||!['low','normal','high','urgent'].includes(input.priority))return{ok:false,error:'حالة الرسالة غير صحيحة.'};const service=getServiceClient(),{data:message}=await service.from('contact_messages').select('email,subject').eq('id',messageId).maybeSingle();if(!message)return{ok:false,error:'الرسالة غير موجودة.'};const{error}=await service.from('contact_messages').update({status:input.status,priority:input.priority,assigned_to:input.assignedTo||null,is_spam:input.spam}).eq('id',messageId);if(error)return{ok:false,error:'تعذّر تحديث الرسالة.'};if(input.note?.trim())await service.from('contact_message_notes').insert({message_id:messageId,author_id:admin.userId,note:input.note.trim()});if(input.reply?.trim()){const{data:delivery}=await service.from('site_settings').select('value').eq('key','email_delivery').maybeSingle(),enabled=Boolean(delivery?.value?.enabled);await service.from('email_outbox').insert({to_email:message.email,subject:`رد: ${message.subject||'رسالتك'}`,body_text:input.reply.trim(),entity_type:'contact_message',entity_id:messageId,status:enabled?'queued':'disabled',provider:delivery?.value?.provider??null,created_by:admin.userId});await service.from('contact_messages').update({status:'replied'}).eq('id',messageId)}await service.from('audit_logs').insert({actor_id:admin.userId,action:'inbox.message_managed',entity_type:'contact_message',entity_id:messageId,meta:{...input,reply:input.reply?true:false}});revalidatePath('/admin/inbox');return{ok:true}}
export async function createUnsubscribeLink(subscriberId:string):Promise<{ok:true;url:string}|{ok:false;error:string}>{const admin=await requirePermission('newsletter.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة القائمة.'};const token=`${crypto.randomUUID()}${crypto.randomUUID()}`.replaceAll('-',''),hash=createHash('sha256').update(token).digest('hex'),{error}=await getServiceClient().from('newsletter_subscribers').update({unsubscribe_token_hash:hash,token_created_at:new Date().toISOString()}).eq('id',subscriberId);if(error)return{ok:false,error:'تعذّر إنشاء الرابط.'};return{ok:true,url:`/unsubscribe/${token}`}}
