'use server'
import{revalidatePath}from'next/cache'
import{requirePermission}from'@/lib/auth/permissions'
import{getServiceClient,hasSupabaseServerSecret}from'@/lib/supabase/server'
import{hasSupabasePublicConfig}from'@/lib/supabase/public-key'
import{normalizeResourceInput}from'@/lib/resources/governance'
type Result={ok:true;id?:string}|{ok:false;error:string}
const configured=()=>hasSupabasePublicConfig()&&hasSupabaseServerSecret()
export async function saveResource(formData:FormData):Promise<Result>{if(!configured())return{ok:false,error:'إدارة الموارد غير مهيّأة في هذه البيئة.'};const admin=await requirePermission('resources.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة الموارد.'};const parsed=normalizeResourceInput(formData);if(!parsed.ok)return parsed;const v=parsed.value,{data,error}=await getServiceClient().rpc('save_resource',{p_id:v.id,p_actor_id:admin.userId,p_slug:v.slug,p_title:v.title,p_excerpt:v.excerpt,p_body:v.body,p_kind:v.kind,p_topic:v.topic,p_duration_minutes:v.durationMinutes,p_external_url:v.externalUrl,p_media_asset_id:v.mediaAssetId,p_transcript:v.transcript,p_captions:v.captions,p_related_product_id:v.relatedProductId,p_status:v.status,p_publish_at:v.publishAt,p_is_featured:v.isFeatured,p_seo_title:v.seoTitle,p_seo_description:v.seoDescription});if(error){if(error.message.includes('resource_slug_exists'))return{ok:false,error:'رابط المورد مستخدم بالفعل.'};if(error.message.includes('resource_media_rights_required'))return{ok:false,error:'الوسيط ليس عامًا أو يفتقد إثبات الحقوق.'};if(error.message.includes('resource_related_product_unpublished'))return{ok:false,error:'العرض المرتبط غير منشور.'};return{ok:false,error:'تعذّر حفظ المورد.'}};for(const path of['/admin/resources','/resources','/search','/'])revalidatePath(path);return{ok:true,id:String(data)}}
export async function deleteResource(id:string):Promise<Result>{if(!configured())return{ok:false,error:'إدارة الموارد غير مهيّأة في هذه البيئة.'};const admin=await requirePermission('resources.manage');if(!admin?.userId)return{ok:false,error:'لا تملكين صلاحية إدارة الموارد.'};const{error}=await getServiceClient().rpc('delete_resource',{p_id:id,p_actor_id:admin.userId});if(error)return{ok:false,error:error.message.includes('archive_resource_before_delete')?'أرشفي المورد قبل حذفه.':'تعذّر حذف المورد.'};for(const path of['/admin/resources','/resources','/search','/'])revalidatePath(path);return{ok:true}}
