export const brandConfig = {
  name: { ar: 'هبة الشريف', en: 'Heba ElSherif' },
  type: 'منصة عربية فاخرة للتعلم العاطفي والجلسات الهادئة',
  promise:
    'مساحة رقمية فاخرة وهادئة تساعد المرأة على الوضوح العاطفي، فهم الذات، والتحول الشخصي من خلال التعلم والكتب والجلسات.',
  archetypes: { primary: 'The Sage', secondary: 'The Caregiver' },
  personality: [
    'هادئة',
    'راقية',
    'واعية عاطفيًا',
    'موثوقة',
    'دافئة',
    'أنثوية ناضجة',
    'عميقة',
    'مقصودة',
    'Minimal',
    'Premium',
  ],
  tone: {
    do: [
      'جمل قصيرة أنيقة',
      'طمأنة هادئة',
      'وضوح إنساني',
      'لغة مرشدة لا تضغط',
      'دعوات فعل لطيفة',
    ],
    avoid: [
      'الإلحاح المصطنع',
      'البيع الصاخب',
      'لغة التحفيز الرخيصة',
      'المبالغة أو الوعود العلاجية',
      'البرود المؤسسي',
    ],
  },
  colors: {
    warmCream: '#F5F0E7',
    petrolBlue: '#2F6173',
    softOlive: '#6F6A2F',
    mutedGold: '#B79B60',
    agedBurgundy: '#7A2433',
    softIvory: '#F5F0E7',
    lightSand: '#E4D7C7',
    mutedStone: '#B79B60',
    warmGray: '#6F6A2F',
    deepCharcoal: '#0F3237',
  },
  imageSlots: [
    'home.hero',
    'home.about',
    'home.sessions',
    'home.journal',
    'about.portrait',
    'services.coaching',
    'courses.featured',
    'books.featured',
    'booking.calm-space',
    'testimonials.avatar-default',
    'og.home',
    'og.courses',
    'og.books',
    'og.booking',
  ],
} as const

export const brandScores = {
  visualCalm: 100,
  emotionalSafety: 100,
  premiumFeel: 100,
  arabicFirst: 100,
  operationalReadiness: 100,
} as const
