'use client'

import { useState } from 'react'
import { deleteAvailabilityException, deleteAvailabilityWindow, deleteBookingSlotOverride, saveAvailabilityException, saveAvailabilityWindow, saveBookingSlotOverride } from '@/lib/actions/booking-admin'
import { Button } from '@/components/ui/Button'

type Rule = { id: string; weekday: number; start_time: string; end_time: string }
type Exception = { id: string; date: string; is_closed: boolean; start_time: string | null; end_time: string | null; kind?: string; reason?: string }
type Override = { id: string; date: string; start_time: string; mode: 'open' | 'closed'; reason?: string }
type Service = { id: string; title: string; rules: Rule[]; exceptions: Exception[]; overrides?: Override[] }
const days = ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت']
const input = 'min-h-11 rounded-xl border border-line bg-surface-raised px-3 py-2 text-ink'

export function AvailabilityManager({ services }: { services: Service[] }) {
  const [message, setMessage] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  async function run(action: () => Promise<{ ok: boolean; error?: string }>) { setBusy(true); setMessage(null); const result = await action(); setMessage(result.ok ? 'تم الحفظ وتحديث صفحة الحجز.' : result.error ?? 'تعذّر الحفظ.'); setBusy(false) }
  if (!services.length) return <p className="text-sm text-taupe">أضيفي خدمة جلسة أولًا لإدارة مواعيدها.</p>
  return <div className="space-y-7">{services.map((service) => <section key={service.id} className="rounded-2xl border border-line bg-ivory/45 p-5">
    <div className="flex items-center justify-between gap-4"><div><h3 className="text-lg font-bold text-deep-teal">{service.title}</h3><p className="text-xs text-text-soft">يمكن إضافة أكثر من نافذة في اليوم نفسه — توقيت القاهرة.</p></div><span className="rounded-full bg-aqua/10 px-3 py-1 text-xs font-bold text-deep-teal">{service.rules.length.toLocaleString('ar-EG')} نافذة</span></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{service.rules.sort((a,b) => a.weekday-b.weekday || a.start_time.localeCompare(b.start_time)).map((rule) => <div key={rule.id} className="flex items-center gap-2 rounded-xl border border-line bg-surface-raised px-3 py-2 text-sm"><b className="text-deep-teal">{days[rule.weekday]}</b><span className="text-text-soft" dir="ltr">{rule.start_time.slice(0,5)}–{rule.end_time.slice(0,5)}</span><button type="button" className="ms-auto font-bold text-burgundy" aria-label={`حذف نافذة ${days[rule.weekday]}`} onClick={() => run(() => deleteAvailabilityWindow(rule.id))}>×</button></div>)}</div>
    <form className="mt-4 grid gap-3 rounded-xl border border-dashed border-antique-gold/40 p-4 sm:grid-cols-4 sm:items-end" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; run(async () => { const result = await saveAvailabilityWindow(new FormData(form)); if (result.ok) form.reset(); return result }) }}><input type="hidden" name="service_id" value={service.id}/><label className="text-sm font-semibold text-deep-teal">اليوم<select name="weekday" className={`mt-1 w-full ${input}`}>{days.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></label><label className="text-sm font-semibold text-deep-teal">من<input name="start_time" type="time" defaultValue="10:00" required className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">إلى<input name="end_time" type="time" defaultValue="14:00" required className={`mt-1 w-full ${input}`}/></label><Button type="submit" size="sm" disabled={busy}>إضافة نافذة</Button></form>
    <form className="mt-6 grid gap-3 border-t border-line pt-5 sm:grid-cols-2 lg:grid-cols-6 lg:items-end" onSubmit={(event) => { event.preventDefault(); const form=event.currentTarget; run(async()=>{const result=await saveAvailabilityException(new FormData(form));if(result.ok)form.reset();return result}) }}><input type="hidden" name="service_id" value={service.id}/><label className="text-sm font-semibold text-deep-teal">التاريخ<input name="date" type="date" required className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">نوع الاستثناء<select name="mode" className={`mt-1 w-full ${input}`}><option value="closed">إغلاق اليوم</option><option value="holiday">إجازة</option><option value="blackout">Blackout date</option><option value="custom">ساعات خاصة</option></select></label><label className="text-sm font-semibold text-deep-teal">من<input name="exception_start" type="time" className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">إلى<input name="exception_end" type="time" className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">سبب داخلي<input name="reason" className={`mt-1 w-full ${input}`}/></label><Button type="submit" variant="secondary" size="sm" disabled={busy}>حفظ الاستثناء</Button></form>
    {service.exceptions.length>0&&<div className="mt-4 flex flex-wrap gap-2">{service.exceptions.map((exception)=><span key={exception.id} className="inline-flex items-center gap-2 rounded-full border border-line bg-surface-raised px-3 py-1.5 text-xs text-text-soft"><b className="text-deep-teal">{exception.date}</b>{exception.kind === 'custom'?`${exception.start_time?.slice(0,5)}–${exception.end_time?.slice(0,5)}`:exception.kind==='holiday'?'إجازة':exception.kind==='blackout'?'Blackout':'مغلق'}<button type="button" className="font-bold text-burgundy" aria-label={`حذف استثناء ${exception.date}`} onClick={()=>run(()=>deleteAvailabilityException(exception.id))}>×</button></span>)}</div>}
    <form className="mt-5 grid gap-3 rounded-xl border border-dashed border-deep-teal/25 p-4 sm:grid-cols-2 lg:grid-cols-5 lg:items-end" onSubmit={(event)=>{event.preventDefault();const form=event.currentTarget;run(async()=>{const result=await saveBookingSlotOverride(new FormData(form));if(result.ok)form.reset();return result})}}><input type="hidden" name="service_id" value={service.id}/><label className="text-sm font-semibold text-deep-teal">تاريخ الـ slot<input name="date" type="date" required className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">الوقت<input name="start_time" type="time" required className={`mt-1 w-full ${input}`}/></label><label className="text-sm font-semibold text-deep-teal">الإجراء<select name="mode" className={`mt-1 w-full ${input}`}><option value="open">فتح يدوي</option><option value="closed">إغلاق يدوي</option></select></label><label className="text-sm font-semibold text-deep-teal">سبب داخلي<input name="reason" className={`mt-1 w-full ${input}`}/></label><Button type="submit" size="sm" disabled={busy}>حفظ الـ slot</Button></form>
    {(service.overrides?.length ?? 0)>0&&<div className="mt-3 flex flex-wrap gap-2">{service.overrides?.map((override)=><span key={override.id} className="inline-flex items-center gap-2 rounded-full border border-line bg-surface-raised px-3 py-1.5 text-xs text-text-soft"><b className="text-deep-teal">{override.date} {override.start_time.slice(0,5)}</b>{override.mode==='open'?'مفتوح يدويًا':'مغلق يدويًا'}<button type="button" className="font-bold text-burgundy" aria-label={`حذف تعديل ${override.date}`} onClick={()=>run(()=>deleteBookingSlotOverride(override.id))}>×</button></span>)}</div>}
  </section>)}{message&&<p className="rounded-xl bg-deep-teal/8 px-4 py-3 text-sm font-semibold text-deep-teal" role="status">{message}</p>}</div>
}
