'use client'

import { useState } from 'react'
import { updateMessageStatus, updateSubscriber } from '@/lib/actions/admin-control'
import { Button } from '@/components/ui/Button'
import { manageInboxMessage } from '@/lib/actions/crm'
import { createUnsubscribeLink } from '@/lib/actions/crm'

export function MessageStatus({id,status}:{id:string;status:string}){
  const [busy,setBusy]=useState(false)
  return <select value={status} disabled={busy} onChange={async(e)=>{setBusy(true);await updateMessageStatus(id,e.target.value);setBusy(false)}} className="min-h-10 rounded-xl border border-line bg-surface-raised px-3 text-sm text-ink"><option value="new">جديدة</option><option value="read">مقروءة</option><option value="replied">تم الرد</option><option value="archived">مؤرشفة</option></select>
}
export function SubscriberControls({id,status}:{id:string;status:string}){
  const [busy,setBusy]=useState(false);const[link,setLink]=useState<string|null>(null)
  return <div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy} onClick={async()=>{setBusy(true);await updateSubscriber(id,status==='subscribed'?'unsubscribed':'subscribed');setBusy(false)}}>{status==='subscribed'?'إلغاء الاشتراك':'إعادة التفعيل'}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);const r=await createUnsubscribeLink(id);if(r.ok){setLink(r.url);await navigator.clipboard?.writeText(`${location.origin}${r.url}`)}setBusy(false)}}>نسخ رابط الإلغاء</Button>{link&&<span className="w-full text-xs text-deep-teal">تم إنشاء رابط آمن ونسخه.</span>}</div>
}
export function MessageWorkspace({message,admins}:{message:{id:string;status:string;priority:string;assignedTo:string|null;spam:boolean;notes:{id:string;note:string;created_at:string}[]};admins:{id:string;label:string}[]}){const[busy,setBusy]=useState(false),[result,setResult]=useState<string|null>(null);const input='min-h-10 rounded-xl border border-line bg-surface-raised px-3 text-sm text-ink';return <details className="min-w-72 rounded-xl border border-line bg-ivory/35"><summary className="cursor-pointer list-none px-3 py-2 text-sm font-bold text-deep-teal">مساحة المتابعة</summary><form className="grid gap-2 border-t border-line p-3" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),r=await manageInboxMessage(message.id,{status:String(f.get('status')),priority:String(f.get('priority')),assignedTo:String(f.get('assigned_to')||''),note:String(f.get('note')||''),spam:f.get('spam')==='on',reply:String(f.get('reply')||'')});setResult(r.ok?'حُفظت المتابعة.':r.error);setBusy(false)}}><div className="grid gap-2 sm:grid-cols-2"><select name="status" defaultValue={message.status} className={input}><option value="new">جديدة</option><option value="read">مقروءة</option><option value="replied">تم الرد</option><option value="archived">مؤرشفة</option></select><select name="priority" defaultValue={message.priority} className={input}><option value="low">منخفضة</option><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div><select name="assigned_to" defaultValue={message.assignedTo??''} className={input}><option value="">غير مسندة</option>{admins.map(admin=><option key={admin.id} value={admin.id}>{admin.label}</option>)}</select><textarea name="note" rows={2} placeholder="ملاحظة داخلية" className={input}/><textarea name="reply" rows={3} placeholder="رد بريدي — سيبقى معطلًا بأمان إن لم يُهيأ مزود البريد" className={input}/><label className="flex items-center gap-2 text-xs"><input name="spam" type="checkbox" defaultChecked={message.spam}/>بريد مزعج</label>{message.notes.length>0&&<div className="space-y-1">{message.notes.map(note=><p key={note.id} className="rounded-lg bg-surface-raised p-2 text-xs">{note.note}</p>)}</div>}<Button type="submit" size="sm" disabled={busy}>حفظ وإرسال الرد للـ outbox</Button>{result&&<p className="text-xs text-deep-teal">{result}</p>}</form></details>}
