'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/Button'
import { createUnsubscribeLink, manageInboxMessage, manageNewsletterSubscriber } from '@/lib/actions/crm'

export function SubscriberControls({id,status}:{id:string;status:string}){
  const [busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[confirmErase,setConfirmErase]=useState(false)
  const manage=async(action:'unsubscribe'|'erase')=>{setBusy(true);setMessage(null);const r=await manageNewsletterSubscriber(id,action);setMessage(r.ok?(action==='erase'?'مُحي سجل البريد مع بقاء التدقيق غير المعرّف.':'أُلغي الاشتراك.') : r.error);setBusy(false)}
  return <div className="flex flex-wrap gap-2">{status==='subscribed'&&<Button type="button" size="sm" variant="secondary" disabled={busy} onClick={()=>manage('unsubscribe')}>إلغاء الاشتراك</Button>}{status==='subscribed'&&<Button type="button" size="sm" variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);const r=await createUnsubscribeLink(id);if(r.ok){await navigator.clipboard?.writeText(`${location.origin}${r.url}`);setMessage('تم تدوير رابط الإلغاء ونسخه من دون تخزين قيمته الخام.')}else setMessage(r.error);setBusy(false)}}>نسخ رابط الإلغاء</Button>}{!confirmErase?<Button type="button" size="sm" variant="burgundy" disabled={busy} onClick={()=>setConfirmErase(true)}>محو البريد</Button>:<><Button type="button" size="sm" variant="burgundy" disabled={busy} onClick={()=>manage('erase')}>تأكيد المحو</Button><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>setConfirmErase(false)}>تراجع</Button></>}{status!=='subscribed'&&<span className="w-full text-xs text-text-soft">إعادة الاشتراك تتم من نموذج الموافقة العام فقط.</span>}{message&&<span role="status" className="w-full text-xs font-semibold text-deep-teal">{message}</span>}</div>
}
export function MessageWorkspace({message,admins}:{message:{id:string;status:string;priority:string;assignedTo:string|null;spam:boolean;notes:{id:string;note:string;created_at:string}[]};admins:{id:string;label:string}[]}){const[busy,setBusy]=useState(false),[result,setResult]=useState<string|null>(null);const input='min-h-10 rounded-xl border border-line bg-surface-raised px-3 text-sm text-ink';return <details className="min-w-72 rounded-xl border border-line bg-ivory/35"><summary className="cursor-pointer list-none px-3 py-2 text-sm font-bold text-deep-teal">مساحة المتابعة</summary><form className="grid gap-2 border-t border-line p-3" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),r=await manageInboxMessage(message.id,{status:String(f.get('status')),priority:String(f.get('priority')),assignedTo:String(f.get('assigned_to')||''),note:String(f.get('note')||''),spam:f.get('spam')==='on',reply:String(f.get('reply')||'')});setResult(r.ok?'حُفظت المتابعة.':r.error);setBusy(false)}}><div className="grid gap-2 sm:grid-cols-2"><select name="status" defaultValue={message.status} className={input}><option value="new">جديدة</option><option value="read">مقروءة</option><option value="replied">تم الرد</option><option value="archived">مؤرشفة</option></select><select name="priority" defaultValue={message.priority} className={input}><option value="low">منخفضة</option><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div><select name="assigned_to" defaultValue={message.assignedTo??''} className={input}><option value="">غير مسندة</option>{admins.map(admin=><option key={admin.id} value={admin.id}>{admin.label}</option>)}</select><textarea name="note" rows={2} placeholder="ملاحظة داخلية" className={input}/><textarea name="reply" rows={3} placeholder="رد بريدي — سيبقى معطلًا بأمان إن لم يُهيأ مزود البريد" className={input}/><label className="flex items-center gap-2 text-xs"><input name="spam" type="checkbox" defaultChecked={message.spam}/>بريد مزعج</label>{message.notes.length>0&&<div className="space-y-1">{message.notes.map(note=><p key={note.id} className="rounded-lg bg-surface-raised p-2 text-xs">{note.note}</p>)}</div>}<Button type="submit" size="sm" disabled={busy}>حفظ وإرسال الرد للـ outbox</Button>{result&&<p className="text-xs text-deep-teal">{result}</p>}</form></details>}
