import type { Metadata } from 'next'
import { PageHero } from '@/components/catalog/PageHero'
import { ProgramCard } from '@/components/catalog/ProgramCard'
import { EmptyState } from '@/components/ui/EmptyState'
import { listPublishedPrograms, type ProgramType } from '@/lib/data/programs'

export const metadata: Metadata = { title: 'البرامج والباقات', description: 'الحزم وبرامج VIP والموارد المجانية المنشورة والجاهزة فعليًا.' }
const filters=[{label:'الكل',value:''},{label:'الحزم',value:'bundle'},{label:'VIP',value:'vip'},{label:'مجاني',value:'free_resource'}]
export default async function ProgramsPage({searchParams}:{searchParams:Promise<{type?:string}>}){const{type}=await searchParams,all=await listPublishedPrograms(),items=['bundle','vip','free_resource'].includes(type??'')?all.filter((item)=>item.type===type as ProgramType):all;return <main><PageHero eyebrow="برامج وباقات" title="اختاري تجربة مكتملة وواضحة" lead="لا يظهر هنا إلا برنامج يملك تكوينًا منشورًا ومسار استحقاق فعليًا؛ لا قوائم انتظار أو عروض غير جاهزة."/><section className="mx-auto max-w-7xl px-6 py-14"><form method="get" className="flex flex-wrap items-end gap-3 rounded-2xl border border-line bg-surface-raised p-4" aria-label="تصفية البرامج"><label className="grid min-w-56 gap-1 text-xs font-bold text-deep-teal">نوع البرنامج<select name="type" defaultValue={type??''} className="min-h-11 rounded-xl border border-line bg-ivory px-3">{filters.map((filter)=><option key={filter.value} value={filter.value}>{filter.label}</option>)}</select></label><button className="min-h-11 rounded-xl bg-deep-teal px-6 font-bold text-on-dark" type="submit">تطبيق الفلتر</button></form>{items.length?<div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map((program)=><ProgramCard key={program.id} program={program}/>)}</div>:<EmptyState className="mt-8" title="لا توجد برامج منشورة بهذه المواصفات" description="لن نعرض حزمة ناقصة أو VIP غير مرتبط أو موردًا مجانيًا بلا محتوى منشور." actionLabel="استكشفي المسارات الأخرى" actionHref="/start-here"/>}</section></main>}
